Repository rackerlabs/zoolander, pull requests merged in 2018-12, with the labels that each got.

#599 MTE-3363: Home Page Banner Dev
  styleguide/_themes/derek/scss/_main.scss
  styleguide/derek/incubation/homepage.ejs
  styleguide/derek/pattern-components/page-banner/_page-banner.scss
  styleguide/derek/pattern-components/page-banner/page-banner.ejs
  styleguide/imgs/derek/banners/homepage-banner-1280.jpg
  styleguide/imgs/derek/banners/homepage-banner-1440.jpg
  styleguide/imgs/derek/banners/homepage-banner-480.jpg
  styleguide/imgs/derek/banners/homepage-banner-768.jpg
  styleguide/imgs/derek/banners/homepage-banner-992.jpg
  styleguide/imgs/derek/banners/homepage-banner.jpg
Labels: Needs Dev Review

#605 fix(homepage): Correct banner path
  styleguide/derek/pattern-components/page-banner/_page-banner.scss
Labels: Needs Dev Review

#610 Add play icon to button
  styleguide/derek/pattern-components/page-banner/_page-banner.scss
  styleguide/imgs/derek/play-btn.svg
Labels: Needs Design Review, Needs Dev Review

#608 feat(styles): updating numerous card patterns for havas colors and text
  styleguide/_themes/global/scss/buttons.scss
  styleguide/derek/global-components/filter-bar/_filter-bar.scss
  styleguide/derek/pattern-components/ias/_ias.scss
  styleguide/derek/pattern-components/key-offers/_key-offers.scss
  styleguide/derek/pattern-components/o365-table/_o365-table.scss
  styleguide/derek/pattern-components/quotes/_quotes.scss
  styleguide/derek/pattern-components/tabs/_tabs.scss
  styleguide/derek/pattern-components/value-props/_value-prop.scss
  styleguide/derek/view-templates/stories/_stories.scss
Labels: Needs Design Review, Needs Dev Review

#611 feat(style): updating styles for resources and customer stories
  styleguide/_themes/global/scss/buttons.scss
  styleguide/_themes/global/scss/swatch.scss
  styleguide/derek/global-components/filter-bar/_filter-bar.scss
  styleguide/derek/incubation/index.jade
  styleguide/derek/pattern-components/resourceCenter-resource/_resourceCenter-resource.scss
  styleguide/derek/pattern-components/resourceCenter-resource/refresh/_resourceCenter-resource.scss
  styleguide/derek/view-templates/events/_events.scss
  styleguide/derek/view-templates/events/events-interior.ejs
  styleguide/derek/view-templates/resource-center/_resource-center.scss
Labels: Needs Design Review, Needs Dev Review

#615 feat(style): update styling for all tables
  styleguide/_layouts/default.jade
  styleguide/_themes/derek/scss/snowflakes/o365.scss
  styleguide/_themes/global/scss/tables.scss
  styleguide/derek/global-theme/tables/_partials/aviator-table.ejs
  styleguide/derek/global-theme/tables/tables.ejs
  styleguide/derek/incubation/solutions.ejs
  styleguide/derek/pattern-components/o365-table/_o365-table.scss
  styleguide/imgs/derek/o365/o365-logo.svg
Labels: Needs Design Review, Needs Dev Review

#614 MTE-3484: Update some patterns for new brand styles
  styleguide/derek/pattern-components/awards/_awards.scss
  styleguide/derek/pattern-components/dedicated-configurator/_dedicated-configurator.scss
  styleguide/derek/pattern-components/service-level-teaser/_service-level-teaser.scss
Labels: Needs Design Review, Needs Dev Review

#619 chore(homepage): Slight animation tweak
  styleguide/derek/incubation/homepage.ejs
  styleguide/derek/pattern-components/page-banner/_page-banner.scss
Labels: Needs Dev Review

#612 MTE-3349: Update interactive map with brand styles
  styleguide/derek/view-templates/interactive-map/_interactive-map.scss
Labels: Needs Design Review, Needs Dev Review

#620 fix(banner): Resolve side-scrolling issue on mobile
  styleguide/derek/pattern-components/page-banner/_page-banner.scss
Labels: Needs Dev Review

#622 feat(style): making challenges items links
  styleguide/derek/pattern-components/challenges-river/_challenges-river.scss
  styleguide/derek/pattern-components/challenges-river/_partials/challenges.ejs
Labels: Needs Design Review, Needs Dev Review

#623 feat(style): minor homepage changes from feedback
  styleguide/derek/global-components/ceiling/_ceiling.scss
  styleguide/derek/global-components/footer/_footer.scss
  styleguide/derek/pattern-components/about-river/_about-river.scss
  styleguide/derek/pattern-components/about-river/about-river.ejs
  styleguide/derek/pattern-components/announcements/_announcements.scss
  styleguide/derek/pattern-components/announcements/_partials/announcement.ejs
  styleguide/derek/pattern-components/challenges-river/_challenges-river.scss
  styleguide/derek/pattern-components/cust-story-river/_cust-story-river.scss
  styleguide/derek/pattern-components/cust-story-river/cust-story-river.ejs
  styleguide/derek/pattern-components/experience-river/_experience-river.scss
  styleguide/derek/pattern-components/industry-river/_industry-river.scss
  styleguide/derek/pattern-components/page-banner/_page-banner.scss
  styleguide/imgs/derek/logos/aeromexico-logo.svg
Labels: Needs Design Review, Needs Dev Review, WIP

#624 feat(style): color change for lp form
  styleguide/_themes/global/scss/forms.scss
Labels: Needs Dev Review
