Repository rackerlabs/zoolander, pull requests merged in 2019-05, with the labels that each got.

#669 feat(modal): Add buy now modal
  styleguide/_themes/derek/scss/_main.scss
  styleguide/derek/global-components/ceiling/ceiling-nonFixed.ejs
  styleguide/derek/global-components/ceiling/ceiling.ejs
  styleguide/derek/global-components/mainnav/mainnav.ejs
  styleguide/derek/global-components/modal/_buy-now.scss
  styleguide/derek/global-components/modal/_modal.scss
  styleguide/derek/global-components/modal/buy-now.ejs
  styleguide/derek/global-components/tracking/tracking.js
  styleguide/derek/global-components/tracking/tracking.spec.js
  styleguide/derek/incubation/homepage.ejs
  styleguide/derek/pattern-components/page-banner/_page-banner.scss
  styleguide/derek/pattern-components/page-banner/page-banner.ejs
  styleguide/global/modal.js
  styleguide/imgs/derek/chat-icon.png
  styleguide/imgs/derek/logos/Product-AWS.svg
  styleguide/imgs/derek/logos/Product-Alibaba.svg
  styleguide/imgs/derek/logos/Product-Azure.svg
  styleguide/imgs/derek/logos/Product-Chat.svg
  styleguide/imgs/derek/logos/Product-Exchange.svg
  styleguide/imgs/derek/logos/Product-Google.svg
  styleguide/imgs/derek/logos/Product-Office365.svg
  styleguide/imgs/derek/logos/Product-OpenStack.svg
  styleguide/imgs/derek/logos/Product-Shopping-cart.svg
  styleguide/imgs/derek/logos/Product-VMware.svg
  styleguide/imgs/derek/logos/azure.png
Labels: WIP

#668 style(gray bgs): removing any gray backgrounds from zoolander
  styleguide/_themes/global/scss/modifiers.scss
  styleguide/derek/_partials/solutions/rivers.ejs
  styleguide/derek/global-theme/buttons.jade
  styleguide/derek/global-theme/swatches.ejs
  styleguide/derek/incubation/office365.ejs
  styleguide/derek/pattern-components/key-offers/key-offers.ejs
  styleguide/derek/pattern-components/product-features/product-features.ejs
  styleguide/derek/patterns/patterns.ejs
  styleguide/derek/templates/landing-page/landingpage-chat.ejs
  styleguide/derek/templates/landing-page/lockedContent-pdf.ejs
  styleguide/derek/templates/landing-page/lockedContent-video.ejs
  styleguide/derek/view-templates/interactive-map/map.ejs
  styleguide/derek/view-templates/resource-center/_resource-center.scss
  styleguide/derek/view-templates/resource-center/resource-center.ejs
Labels: Needs Dev Review

#666 style(update): removing old custom styling
  styleguide/_themes/derek/scss/snowflakes/homepage.scss
  styleguide/_themes/global/scss/bootstrap_variables.scss
  styleguide/derek/pattern-components/headers/_headers.scss
  styleguide/derek/pattern-components/platforms/_platforms.scss
Labels: Needs Dev Review

#671 style(CTA): swapping learn and leave CTA colors
  styleguide/_themes/global/scss/buttons.scss
Labels: Needs Dev Review

#667 style(update): change all static header sizes and line-heights
  styleguide/_themes/global/scss/fonts.scss
  styleguide/derek/incubation/solutions.ejs
Labels: Needs Design Review, WIP
